carnivores:
  alignment: data/carnivores.fasta
  dates: false
  model:
    clock:
      strict:
        clock_rate: 1.0
    site:
      discrete_gamma:
        category_count: 4
        site_gamma_shape:
          lognormal:
            loc: 0.0
            scale: 1.0
    substitution:
      hky:
        frequencies:
          dirichlet:
            concentration:
            - 2.0
            - 2.0
            - 2.0
            - 2.0
        kappa:
          lognormal:
            loc: 0.0
            scale: 2.0
    tree:
      yule:
        birth_rate:
          lognormal:
            loc: 1.0
            scale: 1.5
dengue:
  alignment: data/dengue.fasta
  dates: true
  model:
    clock:
      strict:
        clock_rate:
          lognormal:
            loc: -2.0
            scale: 2.0
    site:
      discrete_weibull:
        category_count: 4
        site_weibull_concentration:
          lognormal:
            loc: 0.0
            scale: 1.0
    substitution:
      hky:
        frequencies:
          dirichlet:
            concentration:
            - 2.0
            - 2.0
            - 2.0
            - 2.0
        kappa:
          lognormal:
            loc: 0.0
            scale: 2.0
    tree:
      coalescent:
        pop_size:
          lognormal:
            loc:  1.0
            scale: 1.5
h3n2:
  alignment: data/h3n2.fasta
  dates: true
  model:
    clock:
      strict:
        clock_rate:
          lognormal:
            loc: -2.0
            scale: 2.0
    site:
      discrete_gamma:
        category_count: 4
        site_gamma_shape:
          lognormal:
            loc: 0.0
            scale: 1.0
    substitution:
      hky:
        frequencies:
          dirichlet:
            concentration:
            - 2.0
            - 2.0
            - 2.0
            - 2.0
        kappa:
          lognormal:
            loc: 0.0
            scale: 2.0
    tree:
      coalescent:
        pop_size:
          lognormal:
            loc:  1.0
            scale: 1.5