carnivores:
  alignment: data/carnivores.fasta
  dates: false
  model:
    clock:
      strict:
        clock_rate: 1.0
    site:
      discrete_gamma:
        category_count: 4
        site_gamma_shape:
          lognormal:
            loc: 0.0
            scale: 1.0
    substitution:
      hky:
        frequencies:
          dirichlet:
            concentration:
            - 2.0
            - 2.0
            - 2.0
            - 2.0
        kappa:
          lognormal:
            loc: 0.0
            scale: 2.0
    tree:
      yule:
        birth_rate:
          lognormal:
            loc: 1.0
            scale: 1.5
h3n2:
  alignment: data/h3n2.fasta
  dates: true
  model:
    clock:
      strict:
        clock_rate:
          lognormal:
            loc: -2.0
            scale: 2.0
    site:
      discrete_gamma:
        category_count: 4
        site_gamma_shape:
          lognormal:
            loc: 0.0
            scale: 1.0
    substitution:
      gtr_rel:
        frequencies:
          dirichlet:
            concentration: [2.0, 2.0, 2.0, 2.0]
        rate_ac:
          gamma:
            concentration: 0.05
            rate: 0.05
        rate_ag:
          gamma:
            concentration: 0.05
            rate: 0.05
        rate_at:
          gamma:
            concentration: 0.05
            rate: 0.05
        rate_cg:
          gamma:
            concentration: 0.05
            rate: 0.05
        rate_gt:
          gamma:
            concentration: 0.05
            rate: 0.05
    tree:
      coalescent:
        pop_size:
          lognormal:
            loc:  1.0
            scale: 1.5