tree:
  coalescent_constant:
    pop_size:
      lognormal:
        loc: 0.1694182
        scale: 1.991141
clock:
  relaxed_lognormal:
    clock_rate:
      lognormal:
        loc: -5.9393044
        scale: 0.6361542
    rate_sd:
      lognormal:
        loc: -1.3318051
        scale: 0.4974137
substitution:
  hky:
    kappa:
      fixed
    frequencies:
      fixed
site:
  none
  

