clock:
  relaxed_lognormal_conjugate:
    rate_loc_precision:
      normalgamma:
        loc: -5.814736203026958
        precision_scale: 0.4
        concentration: 3.3164221870890347
        rate: 0.3028646047813991
site: none
substitution:
  hky:
    frequencies: fixed
    kappa: fixed
tree:
  coalescent_constant:
    pop_size:
      lognormal:
        loc: 0.06367702938213937
        scale: 0.13341435492327347
