tree:
  coalescent_constant:
    pop_size:
      lognormal:
        loc: 2.0
        scale: 0.2
clock:
  relaxed_lognormal:
    clock_rate:
      lognormal:
        loc: -6.0
        scale: 0.8
    rate_sd:
      lognormal:
        loc: -0.64
        scale: 0.14
substitution:
  hky:
    kappa:
      fixed
    frequencies:
      fixed
site:
  none
  

