remote_results: false
project_dir: mahuika:/nesi/project/uoa02746
aggregate_result_dir: out/sim/aggregate
taxa_dir: 20taxa
sequence_dir: 10000sites
model_file: config/model.yaml
submission: false
tex_template: plain #systematic_biology
flu_dataset: h3n2_big