__default__:
  time: 01:00:00
  mem: 16g

beast_run:
  time: 01:00:00
  mem: 16g

beast_results:
  time: 00:10:00
  mem: 2g

variational_fit:
  time: 01:00:00
  mem: 16g

variational_samples:
  time: 00:10:00
  mem: 2g